// <auto-generated />
using System;
using MedicalCardsApp.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalCardsWeb.Migrations
{
    [DbContext(typeof(MedicalCardsDbContext))]
    [Migration("20260511173851_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("MedicalCardsApp.Web.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ScheduledDate")
                        .HasDatabaseName("IX_Appointments_ScheduledDate");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorId = 1,
                            PatientId = 1,
                            ScheduledDate = new DateTime(2026, 5, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Запланирован"
                        },
                        new
                        {
                            Id = 2,
                            DoctorId = 2,
                            PatientId = 2,
                            ScheduledDate = new DateTime(2026, 5, 16, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Запланирован"
                        },
                        new
                        {
                            Id = 3,
                            DoctorId = 3,
                            PatientId = 3,
                            ScheduledDate = new DateTime(2026, 5, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Завершён"
                        },
                        new
                        {
                            Id = 4,
                            DoctorId = 4,
                            PatientId = 4,
                            ScheduledDate = new DateTime(2026, 5, 18, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Запланирован"
                        },
                        new
                        {
                            Id = 5,
                            DoctorId = 1,
                            PatientId = 5,
                            ScheduledDate = new DateTime(2026, 5, 19, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "Завершён"
                        });
                });

            modelBuilder.Entity("MedicalCardsApp.Web.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Specialty")
                        .HasDatabaseName("IX_Doctors_Specialty");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Докторов Иван Петрович",
                            Phone = "+79001111111",
                            Specialty = "Терапевт"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Медведева Анна Сергеевна",
                            Phone = "+79002222222",
                            Specialty = "Кардиолог"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Хирургов Алексей Михайлович",
                            Phone = "+79003333333",
                            Specialty = "Хирург"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Невролова Елена Владимировна",
                            Phone = "+79004444444",
                            Specialty = "Невролог"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Педиатров Дмитрий Олегович",
                            Phone = "+79005555555",
                            Specialty = "Педиатр"
                        });
                });

            modelBuilder.Entity("MedicalCardsApp.Web.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Patients_Email");

                    b.HasIndex("Phone")
                        .HasDatabaseName("IX_Patients_Phone");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1985, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivanov@test.ru",
                            FullName = "Иванов Иван Петрович",
                            Phone = "+79001234567"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1990, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "petrova@test.ru",
                            FullName = "Петрова Анна Сергеевна",
                            Phone = "+79001234568"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1978, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sidorov@test.ru",
                            FullName = "Сидоров Алексей Михайлович",
                            Phone = "+79001234569"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1995, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kozlova@test.ru",
                            FullName = "Козлова Елена Владимировна",
                            Phone = "+79001234570"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1982, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "morozov@test.ru",
                            FullName = "Морозов Дмитрий Олегович",
                            Phone = "+79001234571"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1988, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "novikova@test.ru",
                            FullName = "Новикова Мария Игоревна",
                            Phone = "+79001234572"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1975, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "volkov@test.ru",
                            FullName = "Волков Сергей Андреевич",
                            Phone = "+79001234573"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1992, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lebedeva@test.ru",
                            FullName = "Лебедева Ольга Павловна",
                            Phone = "+79001234574"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(1980, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sokolov@test.ru",
                            FullName = "Соколов Николай Викторович",
                            Phone = "+79001234575"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1987, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pavlova@test.ru",
                            FullName = "Павлова Татьяна Дмитриевна",
                            Phone = "+79001234576"
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(1993, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "semenov@test.ru",
                            FullName = "Семенов Андрей Евгеньевич",
                            Phone = "+79001234577"
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(1979, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fedorova@test.ru",
                            FullName = "Федорова Ирина Николаевна",
                            Phone = "+79001234578"
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(1986, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kuznetsov@test.ru",
                            FullName = "Кузнецов Михаил Сергеевич",
                            Phone = "+79001234579"
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(1991, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "popova@test.ru",
                            FullName = "Попова Светлана Александровна",
                            Phone = "+79001234580"
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(1984, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "vasiliev@test.ru",
                            FullName = "Васильев Павел Иванович",
                            Phone = "+79001234581"
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(1996, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "smirnova@test.ru",
                            FullName = "Смирнова Анна Петровна",
                            Phone = "+79001234582"
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(1977, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "konov@test.ru",
                            FullName = "Конов Игорь Владимирович",
                            Phone = "+79001234583"
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(1989, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mikhailova@test.ru",
                            FullName = "Михайлова Екатерина Сергеевна",
                            Phone = "+79001234584"
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(1983, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alexandrov@test.ru",
                            FullName = "Александров Дмитрий Павлович",
                            Phone = "+79001234585"
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(1994, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "borisova@test.ru",
                            FullName = "Борисова Наталья Игоревна",
                            Phone = "+79001234586"
                        },
                        new
                        {
                            Id = 21,
                            DateOfBirth = new DateTime(1981, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "grigoriev@test.ru",
                            FullName = "Григорьев Сергей Михайлович",
                            Phone = "+79001234587"
                        },
                        new
                        {
                            Id = 22,
                            DateOfBirth = new DateTime(1990, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "egorova@test.ru",
                            FullName = "Егорова Ольга Александровна",
                            Phone = "+79001234588"
                        },
                        new
                        {
                            Id = 23,
                            DateOfBirth = new DateTime(1976, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "zaytsev@test.ru",
                            FullName = "Зайцев Андрей Дмитриевич",
                            Phone = "+79001234589"
                        },
                        new
                        {
                            Id = 24,
                            DateOfBirth = new DateTime(1992, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivanova.m@test.ru",
                            FullName = "Иванова Мария Сергеевна",
                            Phone = "+79001234590"
                        },
                        new
                        {
                            Id = 25,
                            DateOfBirth = new DateTime(1985, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kozlov.p@test.ru",
                            FullName = "Козлов Павел Николаевич",
                            Phone = "+79001234591"
                        },
                        new
                        {
                            Id = 26,
                            DateOfBirth = new DateTime(1988, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lebedev.i@test.ru",
                            FullName = "Лебедев Игорь Владимирович",
                            Phone = "+79001234592"
                        },
                        new
                        {
                            Id = 27,
                            DateOfBirth = new DateTime(1993, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "makarova@test.ru",
                            FullName = "Макарова Татьяна Петровна",
                            Phone = "+79001234593"
                        },
                        new
                        {
                            Id = 28,
                            DateOfBirth = new DateTime(1979, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nikolaev@test.ru",
                            FullName = "Николаев Алексей Сергеевич",
                            Phone = "+79001234594"
                        },
                        new
                        {
                            Id = 29,
                            DateOfBirth = new DateTime(1991, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "orlova@test.ru",
                            FullName = "Орлова Светлана Дмитриевна",
                            Phone = "+79001234595"
                        },
                        new
                        {
                            Id = 30,
                            DateOfBirth = new DateTime(1984, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "romanov@test.ru",
                            FullName = "Романов Михаил Павлович",
                            Phone = "+79001234596"
                        });
                });

            modelBuilder.Entity("MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Treatment")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Diagnosis")
                        .HasDatabaseName("IX_MedicalRecords_Diagnosis");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Острая респираторная вирусная инфекция. Назначено симптоматическое лечение.",
                            Diagnosis = "ОРВИ",
                            DoctorId = 1,
                            PatientId = 1,
                            RecordDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Артериальная гипертензия 2 степени. Рекомендована диета и медикаментозная терапия.",
                            Diagnosis = "Гипертония",
                            DoctorId = 2,
                            PatientId = 2,
                            RecordDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Острый аппендицит. Проведена аппендэктомия.",
                            Diagnosis = "Аппендицит",
                            DoctorId = 3,
                            PatientId = 3,
                            RecordDate = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Хроническая мигрень. Назначены профилактические препараты.",
                            Diagnosis = "Мигрень",
                            DoctorId = 4,
                            PatientId = 4,
                            RecordDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Хронический гастрит. Рекомендована диета стол №5.",
                            Diagnosis = "Гастрит",
                            DoctorId = 1,
                            PatientId = 5,
                            RecordDate = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Description = "Острый бронхит у ребенка. Назначены ингаляции.",
                            Diagnosis = "Бронхит",
                            DoctorId = 5,
                            PatientId = 6,
                            RecordDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Description = "Нарушение сердечного ритма. Проведено обследование.",
                            Diagnosis = "Аритмия",
                            DoctorId = 2,
                            PatientId = 7,
                            RecordDate = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Description = "Острый тонзиллит. Назначены антибиотики.",
                            Diagnosis = "Ангина",
                            DoctorId = 1,
                            PatientId = 8,
                            RecordDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Description = "Остеохондроз поясничного отдела. Рекомендована ЛФК.",
                            Diagnosis = "Остеохондроз",
                            DoctorId = 4,
                            PatientId = 9,
                            RecordDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Description = "Паховая грыжа. Запланирована операция.",
                            Diagnosis = "Грыжа",
                            DoctorId = 3,
                            PatientId = 10,
                            RecordDate = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MedicalCardsApp.Web.Models.Appointment", b =>
                {
                    b.HasOne("MedicalCardsApp.Web.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalCardsApp.Web.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalRecord", b =>
                {
                    b.HasOne("MedicalCardsApp.Web.Models.Doctor", "Doctor")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalCardsApp.Web.Models.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalCardsApp.Web.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("MedicalCardsApp.Web.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("MedicalRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
